[tool.poetry]
name = "forexfproject"
version = "0.1.0"
description = ""
authors = ["Tomas Fancovic (GBS R2R CZ BI) <tomas.fancovic@siemens.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
