# Generated by Django 5.1.3 on 2024-11-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('iso', models.CharField(default='', max_length=3)),
                ('amount', models.IntegerField(default=1)),
                ('dev_buy', models.FloatField(default=0.0)),
                ('dev_sale', models.FloatField(default=0.0)),
                ('dev_mid', models.FloatField(default=0.0)),
                ('vault_buy', models.FloatField(default=0.0)),
                ('vault_sale', models.FloatField(default=0.0)),
                ('vault_mid', models.FloatField(default=0.0)),
                ('cnb', models.FloatField(default=0.0)),
                ('date', models.DateField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
