# Generated by Django 5.1.3 on 2024-11-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('iso', models.CharField(max_length=3)),
                ('dev_buy', models.FloatField()),
                ('dev_sale', models.FloatField()),
                ('dev_mid', models.FloatField()),
                ('vault_buy', models.FloatField()),
                ('vault_sale', models.FloatField()),
                ('vault_cnb', models.FloatField()),
            ],
        ),
    ]
