# Generated by Django 5.1.3 on 2024-11-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexfrenzy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=3, unique=True)),
                ('path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
    ]
