# Generated by Django 5.1.3 on 2024-11-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexfrenzy', '0003_alter_rates_cnb_alter_rates_dev_buy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Watchdog_pref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('Acc_type', models.CharField(max_length=55)),
                ('Currency_Iso', models.CharField(max_length=3)),
                ('Buy', models.FloatField(blank=True, default=0.0, null=True)),
                ('Sell', models.FloatField(blank=True, default=0.0, null=True)),
                ('Middle', models.FloatField(blank=True, default=0.0, null=True)),
                ('Value_max', models.FloatField(blank=True, default=0.0, null=True)),
                ('Value_min', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
